$(document).ready(function(){
	$("#a1").click(function(){
		$("a").removeClass('active');
		$("#a1").addClass('active');
	});
	$("#a2").click(function(){
		$("a").removeClass('active');
		$("#a2").addClass('active');
	});
	$("#a3").click(function(){
		$("a").removeClass('active');
		$("#a3").addClass('active');
	});
	$("#a4").click(function(){
		$("a").removeClass('active');
		$("#a4").addClass('active');
	});
	$("#a5").click(function(){
		$("a").removeClass('active');
		$("#a5").addClass('active');
	});
	$("#a6").click(function(){
		$("a").removeClass('active');
		$("#a6").addClass('active');
	});
	$("#a7").click(function(){
		$("a").removeClass('active');
		$("#a7").addClass('active');
	});
	$("#a8").click(function(){
		$("a").removeClass('active');
		$("#a8").addClass('active');
	});
	$("#a9").click(function(){
		$("a").removeClass('active');
		$("#a9").addClass('active');
	});
	$("#a10").click(function(){
		$("a").removeClass('active');
		$("#a10").addClass('active');
	});
	$("#a11").click(function(){
		$("a").removeClass('active');
		$("#a11").addClass('active');
	});
	$("#a12").click(function(){
		$("a").removeClass('active');
		$("#a12").addClass('active');
	});
});

$( window ).on( "load", function(){
	function image_transition(){
		setTimeout(function(){
			$("#img2").removeClass('trans-image');
			$("#img1").addClass('trans-image');
	    },2000);
	    setTimeout(function(){
			$("#img3").removeClass('trans-image');
			$("#img2").addClass('trans-image');
	    },4000);
	    setTimeout(function(){
			$("#img4").removeClass('trans-image');
			$("#img3").addClass('trans-image');
	    },6000);
	    setTimeout(function(){
			$("#img5").removeClass('trans-image');
			$("#img4").addClass('trans-image');
	    },8000);
	    setTimeout(function(){
			$("#img6").removeClass('trans-image');
			$("#img5").addClass('trans-image');
	    },10000);
	    setTimeout(function(){
			$("#img7").removeClass('trans-image');
			$("#img6").addClass('trans-image');
	    },12000);
	    setTimeout(function(){
			$("#img8").removeClass('trans-image');
			$("#img7").addClass('trans-image');
	    },14000);	
	    setTimeout(function(){
			$("#img9").removeClass('trans-image');
			$("#img8").addClass('trans-image');
	    },15000);	
	    setTimeout(function(){
			$("#img10").removeClass('trans-image');
			$("#img9").addClass('trans-image');
	    },16000);	
	    setTimeout(function(){
			$("#img1").removeClass('trans-image');
			$("#img10").addClass('trans-image');
	    },18000);
	}
	image_transition.call();
	setInterval(function(){
		image_transition.call();
	},18100);
});